//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab08_Vidu01.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=Lab08;Integrated Security=True" +
            ";TrustServerCertificate=True")]
        public string Lab08ConnectionString {
            get {
                return ((string)(this["Lab08ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Lab08.mdf;Int" +
            "egrated Security=True;Connect Timeout=30")]
        public string Lab08ConnectionString1 {
            get {
                return ((string)(this["Lab08ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=F:\\LEARN\\UNIVERSITY\\THLT.NET\\L" +
            "AB08_VIDU01\\LAB08_VIDU01\\LAB08_VIDU01\\LAB08.MDF;Integrated Security=True;TrustSe" +
            "rverCertificate=True")]
        public string F__LEARN_UNIVERSITY_THLT_NET_LAB08_VIDU01_LAB08_VIDU01_LAB08_VIDU01_LAB08_MDFConnectionString {
            get {
                return ((string)(this["F__LEARN_UNIVERSITY_THLT_NET_LAB08_VIDU01_LAB08_VIDU01_LAB08_VIDU01_LAB08_MDFConn" +
                    "ectionString"]));
            }
        }
    }
}
